### ISSUE TITLE
Warning related with deprecated argument

### ISSUE THREAD

**Issue by intention-attention** [cloudposse/terraform-aws-sso#38]
### Describe the Feature

The warning related with account assignments

│ Warning: Argument is deprecated
│ 
│   with module.sso_account_assignments.data.aws_identitystore_user.this["email@company.com"],
│   on .terraform/modules/sso_account_assignments/modules/account-assignments/main.tf line 21, in data "aws_identitystore_user" "this":
│   21: data "aws_identitystore_user" "this" {
│ 
│ Use the alternate_identifier attribute instead.

### Expected Behavior

No warning displayed

### Use Case

When applying account assignments.

### Describe Ideal Solution

Update resource to use recommended/updated argument

**Comment by jagnk** [comment]
Hi I am having the same issue but now it's failing instead of throwing a warning doesn't matter which version of the module I use. 

TF version 1.2.2
AWS provider version v5.0.0
module version 1.1.0

```
╷
│ Error: Unsupported block type
│ 
│   on .terraform/modules/account_assignments/modules/account-assignments/main.tf line 25, in data "aws_identitystore_user" "this":
│   25:   filter {
│ 
│ Blocks of type "filter" are not expected here.

```

You merged recently a fix for data "aws_identitystore_group" in https://github.com/cloudposse/terraform-aws-sso/pull/35/files . This need to be fixed for data "aws_identitystore_user" too.

Could you fix it please as it is blocking my work.
